version: "3"

services:
  db:
    build: MariaDB/
    env_file:
      - .env
    volumes:
      #- /home/med/dev/42/inception-volumes/mariadb:/var/lib/mysql
      - ./mariadb_volume:/var/lib/mysql

  nginx:
    build: Nginx/
    ports:
      - 443:443
    volumes:
      - ./wordpress_volume:/var/www/localhost/htdocs/
    depends_on:
      - wordpress

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

  wordpress:
    build: Wordpress/
    env_file:
      - .env
    volumes:
      - ./wordpress_volume:/var/www/html
    depends_on:
      - db

# Host-mounted volume: /host/path:/container/path (Binded to the host given path)
# Named volume: named_volume_name:/container/path (Data persists after removing container, accessible by other containers, created in /var/lib/docker/volumes on host)
# Anonymous volume: /container/path/only (After container is removed, data is erased, volume cannot be accessed by another container)
# Networking: https://docs.docker.com/network/ , https://forums.docker.com/t/set-default-network-name-for-compose/36779/2

# Simply change the name since all containers use the same network
networks:
  default:
    name: inception-network