version: "3.9"

services:
  mariadb:
    build: MariaDB/
    environment:
      - MARIADB_USER=wordpress
      - MARIADB_PASSWORD=wordpress
#    volumes:
#      - /home/med/dev/42/inception-volumes/mariadb:/var/lib/mysql
  adminer:
    image: adminer
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    restart: always
    ports:
      - 7777:8080
#    networks:
#      - web

# Host-mounted volume: /host/path:/container/path (Binded to the host given path)
# Named volume: named_volume_name:/container/path (Data persists after removing container, accessible by other containers, created in /var/lib/docker/volumes on host)
# Anonymous volume: /container/path/only (After container is removed, data is erased, volume cannot be accessed by another container)

#networks:
#  web: