CREATE DATABASE $MARIADB_WP_DB_NAME;

ALTER USER 'root'@'localhost' IDENTIFIED BY '$MARIADB_ROOT_PASSWORD';

CREATE USER '$MARIADB_WP_USER'@'localhost' IDENTIFIED BY '$MARIADB_WP_PASSWORD';
GRANT ALL PRIVILEGES ON $MARIADB_WP_DB_NAME.* TO '$MARIADB_WP_USER'@'%' IDENTIFIED BY '$MARIADB_WP_PASSWORD' WITH GRANT OPTION;

CREATE USER '$MARIADB_WP_ADMIN_USER'@'localhost' IDENTIFIED BY '$MARIADB_WP_ADMIN_PASSWORD';
GRANT ALL PRIVILEGES ON $MARIADB_WP_DB_NAME.* TO '$MARIADB_WP_ADMIN_USER'@'%' IDENTIFIED BY '$MARIADB_WP_ADMIN_PASSWORD' WITH GRANT OPTION;


FLUSH PRIVILEGES;