CREATE DATABASE wp_db;

CREATE USER '$MARIADB_WP_USER'@'localhost' IDENTIFIED BY '$MARIADB_WP_PASSWORD';

GRANT ALL PRIVILEGES ON wp_db.* TO '$MARIADB_WP_USER'@'%' IDENTIFIED BY '$MARIADB_WP_PASSWORD' WITH GRANT OPTION;

FLUSH PRIVILEGES;